# action.yml
name: 'tekh-action'
description: 'Update an existing tekh repository to latest'
inputs:
  chart:
    description: helm chart to use
    required: true
  url:
    description: helm url to use
    required: true
  namespace:
    description: namespace in which to install the application
    required: true
  name:
    description: name of the application to install
    required: true
  values:
    description: values file to use
    required: false
    default: "__UNSET__"
  additional:
    description: Any additional arguments to pass to tekh
    required: false
    default: "__UNSET__"
  update_documentation:
    description: 'Whether to update the documentation (default false)'
    required: false
    default: 'true'
  documentation_file:
    description: >-
      Documentation file to update if `update_documentation` is `true` (default README.md)
    required: false
    default: 'README.md'
outputs:
  version:
    description: Chart version of upgrade
  changed:
    description: Whether or not anything changed
  commit_message:
    description: Commit message generated from version change
runs:
  using: 'docker'
  image: docker://public.ecr.aws/skedulo/tekh:v0.7.3-1-gef24835
  args:
    - ${{ inputs.chart }}
    - ${{ inputs.url }}
    - ${{ inputs.name }}
    - ${{ inputs.namespace }}
    - ${{ inputs.values }}
    - ${{ inputs.additional }}
    - ${{ inputs.update_documentation }}
    - ${{ inputs.documentation_file }}
